name: MultiSummon
version: ${project.version}
main: me.triadtriangle.multisummon.MultiSummon
api-version: 1.16
authors: [ TriadTriangle ]
description: Allows for summoning multiple entities with 1 command
commands:
  multisummon:
    description: Used to summon multiple entities
    usage: /<command> this is the updated version
    aliases: [ms]
